<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headTitle(); ?>
<link rel="shortcut icon" href="/themes/default/images/favicon.ico" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<?php echo $this->headMeta(); ?>

<link rel="stylesheet" type="text/css" href="/themes/default/css/main.css" />
<?php echo $this->headLink(); ?>
<script type="text/javascript" src="/themes/default/js/jquery-1.5.min.js"></script>
<?php echo $this->headScript(); ?>
</head>
<body>
<?php echo $this->layout()->content?>
</body>
</html>